spring:
  application:
    name: payroll-api
   
server:
  port: 8100
eureka:
  client:
    service-url:
       default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 0